onlyBuiltDependencies:
  - '@anthropic-ai/claude-code'
  - better-sqlite3
  - esbuild
  - protobufjs
  - sharp
  - tree-sitter
  - tree-sitter-bash
  - tree-sitter-c
  - tree-sitter-cli
  - tree-sitter-cpp
  - tree-sitter-css
  - tree-sitter-dart
  - tree-sitter-go
  - tree-sitter-html
  - tree-sitter-java
  - tree-sitter-javascript
  - tree-sitter-json
  - tree-sitter-kotlin
  - tree-sitter-lua
  - tree-sitter-php
  - tree-sitter-python
  - tree-sitter-ruby
  - tree-sitter-rust
  - tree-sitter-swift
  - tree-sitter-toml
  - tree-sitter-typescript
  - tree-sitter-yaml
